# Generated by Django 4.0.7 on 2022-08-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_address_state_alter_cart_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
        ),
    ]
