# Generated by Django 4.0.7 on 2022-09-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_productoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryoffer',
            name='category',
        ),
    ]
