# Generated by Django 4.0.7 on 2022-09-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_remove_subcategoryoffer_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=100)),
                ('valid_from', models.DateField(auto_now=True)),
                ('valid_to', models.DateField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
