# Generated by Django 4.0.7 on 2022-09-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='active',
            new_name='is_active',
        ),
    ]
