# Generated by Django 4.0.7 on 2022-09-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0013_coupons_description_coupons_max_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='user',
        ),
    ]
