# Generated by Django 4.1 on 2022-08-13 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_subcategories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='media/Products_Image')),
                ('images_two', models.ImageField(null=True, upload_to='media/Products_Image')),
                ('images_three', models.ImageField(null=True, upload_to='media/Products_Image')),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_description', models.TextField()),
                ('product_long_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.categories')),
                ('subcategories', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.subcategories')),
            ],
        ),
    ]
