# Generated by Django 4.1 on 2022-08-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_products_images_alter_products_images_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='Subcategory_Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
