# Generated by Django 4.1 on 2022-08-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_subcategories_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.RemoveField(
            model_name='products',
            name='images_three',
        ),
        migrations.RemoveField(
            model_name='products',
            name='images_two',
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='Subcategory_Image',
            field=models.FileField(upload_to='Subcategory_Image'),
        ),
    ]
