# Generated by Django 4.1 on 2022-08-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_subcategories_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='Subcategory_Image',
            field=models.FileField(upload_to='Product_images'),
        ),
    ]
