# Generated by Django 4.1 on 2022-08-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_subcategories_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='Subcategory_Image',
            field=models.ImageField(default=True, upload_to='media/'),
        ),
    ]
