# Generated by Django 4.1 on 2022-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_subcategories_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_image',
            field=models.ImageField(default=True, upload_to='Products_Image'),
        ),
    ]
