# Generated by Django 4.0.7 on 2022-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images_three',
            field=models.ImageField(null=True, upload_to='Products_Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='images_two',
            field=models.ImageField(null=True, upload_to='Products_Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
