# Generated by Django 4.0.7 on 2022-08-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_products_images_three_products_images_two_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='images_three',
            new_name='Productimage_three',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='images_two',
            new_name='Productimage_two',
        ),
    ]
