# Generated by Django 4.0.7 on 2022-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_rename_images_three_products_productimage_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
