# Generated by Django 4.0.7 on 2022-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Productimage_three',
            field=models.ImageField(default=True, null=True, upload_to='Products_Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Productimage_two',
            field=models.ImageField(default=True, null=True, upload_to='Products_Image'),
        ),
    ]
