# Generated by Django 4.0.7 on 2022-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_alter_products_productimage_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(null=True),
        ),
    ]
