# Generated by Django 4.0.7 on 2022-09-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_products_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
