# Generated by Django 4.0.7 on 2022-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_alter_products_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
