# Generated by Django 4.0.7 on 2022-08-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_payment_status_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order Confirmed', 'order Confirmed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned')], default='Order Confirmed', max_length=100, null=True),
        ),
    ]
