# Generated by Django 4.0.7 on 2022-09-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_order_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Order Pending', max_length=100, null=True),
        ),
    ]
