# Generated by Django 4.0.7 on 2022-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=0, max_length=15, null=True),
        ),
    ]
