# Generated by Django 4.0.7 on 2022-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_walletdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletdetails',
            name='wallet',
        ),
        migrations.AddField(
            model_name='walletdetails',
            name='wallet',
            field=models.ManyToManyField(null=True, to='Order.wallet'),
        ),
    ]
