# Generated by Django 4.0.7 on 2022-09-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_remove_walletdetails_wallet_walletdetails_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletdetails',
            name='wallet',
        ),
        migrations.AddField(
            model_name='walletdetails',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.wallet'),
        ),
    ]
